version: "2"
services:
  diagnose-backend:
    restart: always
    container_name: diagnose-backend
    image: diagnose-backend:latest
    ports:
      - 8080:8080
  diagnose-frontend:
    restart: always
    container_name: diagnose-frontend
    image: diagnose-web:latest
    volumes:
      - /var/www:/var/www
    depends_on:
      - diagnose-backend
    ports:
      - 6789:6789
